### ISSUE TITLE
🔧 Missing closing `</section>` tag for first `<section>` on join page

### ISSUE THREAD

**Issue by rzmk** [ahkim103/ROCCWebsite#1]
On `join.html` I noticed there's no closing `</section>` tag for line 13's opening `<section>` tag.

https://github.com/ahkim103/ROCCWebsite/blob/e7185a74ae21efc7bcc51e5012e86b8165702014/join.html#L13

**Comment by ahkim103** [comment]
Fixed it. Thanks for bringing it to my attention!
